# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

pool:
  vmImage: ubuntu-22.04

variables:
  # Version
  major: 2
  minor: 0
  revision: $[ counter(format('{0}.{1}.{2}', variables['major'], variables['minor'], variables['Build.SourceBranchName']), 0) ]
  versionStr: $(major).$(minor).$(revision)
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'DecianX Docker Registry (nexus-registry.decian.net)'

  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    docker_tags: |
      latest
      $(major)
      $(major).$(minor)
      $(major).$(minor).$(revision)
  ${{ else }}:
    docker_tags: |
      branch_$(major).$(minor).$(revision)
name: $(major).$(minor).$(revision)$(Rev:.r)_$(Build.SourceBranchName)

steps:
  # - task: DockerCompose@0
  #   displayName: 'docker-compose build'
  #   inputs:
  #     containerregistrytype: 'Container Registry'
  #     dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
  #     dockerComposeFile: 'docker-compose-build.yml'
  #     action: 'Build services'
  #     additionalImageTags: '$(docker_tags)'
  #     includeLatestTag: true
  #     additionalArguments: '--parallel'

  # - task: DockerCompose@0
  #   displayName: 'docker-compose push'
  #   inputs:
  #     containerregistrytype: 'Container Registry'
  #     dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
  #     dockerComposeFile: 'docker-compose.yml'
  #     action: 'Push services'
  #     additionalImageTags: '$(docker_tags)'
  #     includeLatestTag: true
  #     additionalArguments: '--parallel'

  - task: Docker@2
    displayName: Build and push webApp to container registry
    inputs:
      command: buildAndPush
      repository: 'dx-iris-web'
      dockerfile: '$(Build.SourcesDirectory)/docker/webApp/Dockerfile'
      containerRegistry: $(dockerRegistryServiceConnection)
      buildContext: .
      tags: |
        $(docker_tags)

  - task: Docker@2
    displayName: Build and push db to container registry
    inputs:
      command: buildAndPush
      repository: 'dx-iris-db'
      dockerfile: '$(Build.SourcesDirectory)/docker/db/Dockerfile'
      containerRegistry: $(dockerRegistryServiceConnection)
      buildContext: ./docker/db
      tags: |
        $(docker_tags)

  - task: Docker@2
    displayName: Build and push nginx to container registry
    inputs:
      command: buildAndPush
      repository: 'dx-iris-nginx'
      dockerfile: '$(Build.SourcesDirectory)/docker/nginx/Dockerfile'
      containerRegistry: $(dockerRegistryServiceConnection)
      buildContext: ./docker/nginx
      arguments: --NGINX_CONF_GID=1234 --NGINX_CONF_FILE=nginx.conf
      tags: |
        $(docker_tags)
