version: "3.5"
services:
  db:
    build:
      context: docker/db
    container_name: iriswebapp_db
    image: iriswebapp_db:v2.3.3

  app:
    build:
      context: .
      dockerfile: docker/webApp/Dockerfile
    image: iriswebapp_app:v2.3.3
    container_name: iriswebapp_app

  nginx:
    build:
      context: ./docker/nginx
      args:
        NGINX_CONF_GID: 1234
        NGINX_CONF_FILE: nginx.conf
    image: iriswebapp_nginx:v2.3.3
    container_name: iriswebapp_nginx

