#!/bin/bash
set -e

POSTGRES="psql --username ${POSTGRES_USER}"

echo "Creating database role: ${POSTGRES_ADMIN_USER}"

# Create the admin user with proper privileges
$POSTGRES <<-EOSQL
CREATE USER ${POSTGRES_ADMIN_USER} WITH CREATEDB SUPERUSER PASSWORD '${POSTGRES_ADMIN_PASSWORD}';
\c iris_db;
CREATE EXTENSION IF NOT EXISTS pgcrypto CASCADE;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" CASCADE;
GRANT ALL PRIVILEGES ON DATABASE iris_db TO ${POSTGRES_ADMIN_USER};
GRANT ALL ON SCHEMA public TO ${POSTGRES_ADMIN_USER};
ALTER SCHEMA public OWNER TO ${POSTGRES_ADMIN_USER};
EOSQL

echo "Database initialization completed successfully"